name: Instagram Video Upload - Src

on:
  schedule:
    - cron: '32 10 * * *' # Runs every day at 10:32 AM UTC
  workflow_dispatch:  # This enables manual triggering of the workflow

jobs:
  upload:
    runs-on: self-hosted
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'
    - name: Random Time Sleep
      shell: powershell
      run: Start-Sleep -Duration (New-TimeSpan -Minutes (1..2 | Get-Random))
      
    - name: Install dependencies
      shell: powershell
       #upgrade --all
      run: |
        $wingetPath = "C:\Program Files\WindowsApps\Microsoft.DesktopAppInstaller_1.23.1911.0_x64__8wekyb3d8bbwe\winget.exe"
        $pythonPath = "C:\Users\LocalAdmin\AppData\Local\Microsoft\WindowsApps\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\python.exe"
        Invoke-Expression "& '$wingetPath' upgrade --all"
        Invoke-Expression "& '$wingetPath' install ffmpeg  --exact --disable-interactivity --accept-source-agreements --accept-package-agreements"

    - name: Install dependencies
      shell: cmd
       #upgrade --all
      run: |
        python -m pip install --upgrade pip
        python -m pip install instagrapi Pillow moviepy BeautifulSoup4 requests
    
    - name: Run upload script
      continue-on-error: true  # Only if you want to suppress all errors
      shell: cmd
      env:
        USERNAME1: ${{ secrets.USERNAME1 }}
        PASSWORD1: ${{ secrets.PASSWORD1 }}
        SESSION1: ${{ secrets.SESSION1 }}
        USERNAME2: ${{ secrets.USERNAME2 }}
        PASSWORD2: ${{ secrets.PASSWORD2 }}
        SESSION2: ${{ secrets.SESSION2 }}
        USERNAME3: ${{ secrets.USERNAME3 }}
        PASSWORD3: ${{ secrets.PASSWORD3 }}
        SESSION3: ${{ secrets.SESSION3 }}
        USERNAME4: ${{ secrets.USERNAME4 }}
        PASSWORD4: ${{ secrets.PASSWORD4 }}
        SESSION4: ${{ secrets.SESSION4 }}
      run: |
        python auto-insta-upload.py


