name: Instagram Video Upload - Src

on:
  schedule:
    - cron: '32 10 * * *' # Runs every day at 10:32 AM UTC
  workflow_dispatch:  # This enables manual triggering of the workflow

jobs:
  upload:
    runs-on: self-hosted
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    
    - name: Install dependencies
      shell: powershell
       #upgrade --all
      run: |
        $wingetPath = Join-Path (Get-AppxPackage Microsoft.DesktopAppInstaller).InstallLocation "winget.exe"
        Invoke-Expression "& '$wingetPath' upgrade --all "
        Invoke-Expression "& '$wingetPath' install -y ffmpeg"
        python -m pip install --upgrade pip
        pip install instagrapi==1.13.0 Pillow==9.0.1 moviepy==1.0.3 BeautifulSoup4==4.10.0 requests==2.27.1
    
    - name: Run upload script
      continue-on-error: true  # Only if you want to suppress all errors
      shell: powershell
      env:
        USERNAME1: ${{ secrets.USERNAME1 }}
        PASSWORD1: ${{ secrets.PASSWORD1 }}
        SESSION1: ${{ secrets.SESSION1 }}
        USERNAME2: ${{ secrets.USERNAME2 }}
        PASSWORD2: ${{ secrets.PASSWORD2 }}
        SESSION2: ${{ secrets.SESSION2 }}
        USERNAME3: ${{ secrets.USERNAME3 }}
        PASSWORD3: ${{ secrets.PASSWORD3 }}
        SESSION3: ${{ secrets.SESSION3 }}
        USERNAME4: ${{ secrets.USERNAME4 }}
        PASSWORD4: ${{ secrets.PASSWORD4 }}
        SESSION4: ${{ secrets.SESSION4 }}
      run: |
        python auto-insta-upload.py


